# Generated by Django 5.2.1 on 2025-05-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Enter a feature or bullet point for this product', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='The order in which this bullet point appears in the list')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='api.product')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
                'ordering': ['order'],
            },
        ),
    ]
