# Generated by Django 5.2.1 on 2026-02-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_test_user',
            field=models.BooleanField(default=False),
        ),
    ]
