"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import cloudinary
import os
load_dotenv()

# import pymysql
# pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Configuration
cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME'),
    api_key=os.environ.get('CLOUDINARY_API_KEY'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
    secure=True
)

# stripe
STRIPE_PUBLISHABLE_KEY = os.environ.get(
    'STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get(
    'STRIPE_SECRET_KEY', '')
# UPDATED: Change default from localhost to HTTPS domain

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://easy-shop.biz')

# Validate that required environment variables are set
if not STRIPE_SECRET_KEY:
    raise ValueError("STRIPE_SECRET_KEY environment variable is not set")
if not STRIPE_PUBLISHABLE_KEY:
    raise ValueError("STRIPE_PUBLISHABLE_KEY environment variable is not set")

# print('=----- api key --------')
# print(os.environ.get('CLOUDINARY_API_SECRET'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

# Django won't serve static files with DEBUG=False. Add WhiteNoise:
DEBUG = os.environ.get('DEBUG', 'False') == 'True'


# UPDATED: Add all your new domains
ALLOWED_HOSTS = [
    '.railway.app',
    'localhost',
    '127.0.0.1',
    '.elasticbeanstalk.com',
    '.eu-north-1.elasticbeanstalk.com',
    '172.31.0.81',
    '172.31.2.196',
    '172.31.17.46',
    'api.easy-shop.biz',                    # Your API domain
    'easy-shop.biz',                        # Your main domain
    'www.easy-shop.biz',                    # WWW version
    'django-api-prod.eba-2ff8w2hp.eu-north-1.elasticbeanstalk.com',  # Keep existing
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Our apps
    'api',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add this at the top
    # Other middleware...
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # add for white noise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# UPDATED: CORS settings - added API subdomain
CORS_ALLOW_ALL_ORIGINS = False  # Changed to False for better security
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",                # Local development
    "https://easy-shop.biz",                # Your main domain (HTTPS)
    "https://api.easy-shop.biz",            # ADDED: Your API domain
    "https://www.easy-shop.biz",            # WWW version (HTTPS)
    "https://django-shop-frontend.vercel.app",  # Backup Vercel domain
]

# UPDATED: CSRF settings for cross-subdomain support
# CHANGED: From 'Lax' to 'None' for cross-subdomain
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True           # Keep True for HTTPS
CSRF_COOKIE_DOMAIN = '.easy-shop.biz'  # ADDED: Share cookies across subdomains
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',                # Local development
    'https://easy-shop.biz',                # Your main domain
    'https://api.easy-shop.biz',            # Your API domain
    'https://www.easy-shop.biz',            # WWW version
    'https://django-shop-frontend.vercel.app',  # Backup
]
CSRF_USE_SESSIONS = False     # Store CSRF token in cookie, not session

# UPDATED: Security settings for HTTPS production
# Temporarily disable SSL redirect for testing
SECURE_SSL_REDIRECT = False                # TEMP: Disable for testing
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # For AWS ELB
# SECURE_HSTS_SECONDS = 31536000             # TEMP: Disable for testing
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True      # TEMP: Disable for testing
SECURE_CONTENT_TYPE_NOSNIFF = True         # Additional security
SECURE_BROWSER_XSS_FILTER = True           # Additional security

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# UPDATED: Session cookies for cross-subdomain support
# CHANGED: From 'Lax' to 'None' for cross-subdomain
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True        # Keep True for HTTPS
# ADDED: Share cookies across subdomains
SESSION_COOKIE_DOMAIN = '.easy-shop.biz'

# Common session-related settings in settings.py
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds (default)
# SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access (security feature)

# SameSite Cookie Options -- 1. Strict | 2. Lax (Default) | 3. None | 4. Unspecified (No SameSite Attribute)
# In Django, you can control this behavior with the setting:
# SESSION_COOKIE_SAMESITE = 'Lax'  # Default in modern Django
# CSRF_COOKIE_SAMESITE = 'Lax'     # Default in modern Django

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('ENGINE'),
        'NAME': os.environ.get('NAME'),
        'USER': os.environ.get('USER'),
        'PASSWORD': os.environ.get('PASSWORD'),
        'HOST': os.environ.get('HOST'),
        'PORT': os.environ.get('PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
#
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add at the end of the file
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Override for local development
if DEBUG:
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_DOMAIN = None       # Don't restrict to a domain locally
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_DOMAIN = None
